# modules.translate

from disnake import TextInputStyle, ui, Embed, Color
from modules.utils.GPT import OpenAIAgent
from disnake.ext import commands
import asyncio
import disnake
import re

TIMEOUT = 300
TRANSLATE_MODAL_ID = 'translate_modal'

class TranslateCog(commands.Cog):
    def __init__(self, client):
        self.client = client
        self.chat_engine = OpenAIAgent.from_tools(
            [],
            system_prompt="You are a translator. Translate the following message to the specified language. Provide only the translated text without any additional explanations.",
            verbose=False
        )

    @commands.slash_command()
    async def translate(self, inter: disnake.ApplicationCommandInteraction):
        await self.show_translate_modal(inter)

    @commands.message_command(name="Translate Message")
    async def translate_message(self, inter: disnake.MessageCommandInteraction):
        await self.show_translate_modal(inter, inter.target.content, inter.target.author.display_name)

    async def show_translate_modal(self, inter, message=None, author=None):
        await inter.response.send_modal(
            title="Translate",
            custom_id=TRANSLATE_MODAL_ID,
            components=[
                ui.TextInput(label="Target Language", placeholder="Enter the target language (e.g., Spanish)", custom_id="target_lang", style=TextInputStyle.short),
                ui.TextInput(label="Message", value=message, placeholder="Enter the message to translate" if not message else None, custom_id="message", style=TextInputStyle.paragraph, required=not bool(message))
            ],
        )
        try:
            modal_inter = await inter.client.wait_for('modal_submit', check=lambda i: i.custom_id == TRANSLATE_MODAL_ID and i.author.id == inter.author.id, timeout=TIMEOUT)
            message, target_lang = modal_inter.text_values.get('message', ''), modal_inter.text_values.get('target_lang', '')
            translated_text = await self.translate_text(self.replace_mentions(inter, message), target_lang)
            await modal_inter.response.send_message(embed=self.create_translation_embed(inter, message, translated_text, target_lang, author) if translated_text else "❌ Translation error.")
        except asyncio.TimeoutError:
            await inter.followup.send("⏰ Translation request timed out.")

    def replace_mentions(self, inter, message):
        return re.sub(r'<@!?(\d+)>', lambda m: f"@{inter.guild.get_member(int(m.group(1))).display_name}" if inter.guild.get_member(int(m.group(1))) else m.group(0), message)

    async def translate_text(self, message, target_lang):
        response = await asyncio.to_thread(self.chat_engine.chat, f"Translate this to {target_lang}: {message}")
        return response.response.strip() if response and response.response else None

    def create_translation_embed(self, inter, original_message, translated_text, target_lang, author):
        embed = Embed(title=f"🌐 Translation to {target_lang}", color=Color.blue())
        embed.add_field(name=f"📝 Original{f' (by {author})' if author else ''}", value=f"```{original_message}```", inline=False)
        embed.add_field(name="🔄 Translated", value=f"```{translated_text}```", inline=False)
        embed.set_author(name=f"Requested by {inter.author.display_name}", icon_url=inter.author.avatar.url if inter.author.avatar else None)
        embed.set_footer(text="⚠️ This translation was generated by an AI language model and may not be perfectly accurate.")
        return embed

def setup(client):
    client.add_cog(TranslateCog(client))