version: '3.8'

services:
  frogbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frogbot
    volumes:
      - .:/app
      - ./user_points.db:/app/user_points.db
      - ./config.yaml:/app/config.yaml
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: python core.py
    restart: unless-stopped

volumes:
  user_points_data:
  config_data: