version: '3.8'

services:
  frogbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frogbot
    volumes:
      - .:/app
      - ./user_points.db:/app/user_points.db
      - ./config.yaml:/app/config.yaml
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: python core.py
    restart: unless-stopped

  backup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./user_points.db:/app/user_points.db
      - ./config.yaml:/app/config.yaml
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    command: /usr/sbin/cron -f -L 15
    depends_on:
      - frogbot

volumes:
  user_points_data:
  config_data:
