# Configuration file for the bot. This will change and remove all comments after the first run of the bot.
# ----- RENAME THIS FILE TO config.yaml BEFORE RUNNING THE BOT -----

# This is required
# Discord Bot Token
# Replace with your bot's token from the Discord Developer Portal
DISCORD_TOKEN: "(REPLACE)"

# This is optional
# OpenAI API Key
# Replace with your OpenAI API key
# OPENAI_API_KEY: "(REPLACE IF USED)"

# Database file
# Replace with the name you want your database file to be
# DATABASE_FILE: "(REPLACE IF USED)"

# GitHub Token
# Replace with your GitHub token if needed for GitHub API access
# GITHUB_TOKEN: "(REPLACE IF USED)"

# Do not change
# Restart channel ID
# This is where your bot will put the last channel ID it was in before restarting
restart_channel_id: 
